name: Go tests with PostgreSQL (GitHub Actions services)

on:
  workflow_dispatch:

jobs:
  tests:
    name: Go tests with PostgreSQL as GitHub Actions service
    runs-on: ubuntu-latest

    steps:
      - name: TODO: Implement testing with PostgreSQL via GitHub Actions service
        run: echo "Coming soon: Go tests using PostgreSQL service"
